green.yp.backend.host=http://localhost:8081
green.yp.reference.url=http://localhost:8081/reference
green.yp.account.url=http://localhost:8081/account
green.yp.usps.address.api.url=https://secure.shippingapis.com/ShippingAPI.dll
greem.yp.usps.address.api.userId=3GREEN0726X57
spring.cloud.openfeign.httpclient.hc5.enabled=true
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000
#spring.cloud.openfeign.client.config.default.loggerLevel=basic
vaadin.closeIdleSessions=true
vaadin.heartbeatInterval=600